FROM mariadb:11

# Variables d'environnement pour configurer MariaDB
ENV MYSQL_USER=guestuser
ENV MYSQL_PASSWORD=guestpassword
ENV MYSQL_DATABASE=guestbook
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Copier le script d'initialisation de la base de données
COPY init_db.sql /docker-entrypoint-initdb.d/

# Exposer le port 3306
EXPOSE 3306 